# Generated by Django 3.0.7 on 2020-10-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201023_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(default='User', max_length=30),
        ),
    ]
